#host: "localhost"
#port: ""
#database: "testdriver"
#user: "root"
#password: ""

read:
  host: "localhost"
  port: "3306"
  database: "driver_disconnect" #"pickme"
  user: "root"
  password: ""
  max_idle_connections: 50
  max_open_connections: 100

write:
  host: "localhost" #"10.240.0.17"
  port: "3306"
  database: "driver_disconnect" #"pickme"
  user: "root"
  password: ""
  max_idle_connections: 50
  max_open_connections: 10

timezone: "Asia/Colombo"
